/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.LocaZilla.view;

import com.LocaZilla.control.categoria.CategoriaControle;
import com.LocaZilla.control.modelo.ModeloControle;
import com.LocaZilla.control.modelo.IModeloControle;
import com.LocaZilla.control.veiculo.IVeiculoControle;
import com.LocaZilla.control.veiculo.VeiculoControle;
import com.LocaZilla.model.modelo.Modelo;
import com.LocaZilla.model.veiculo.Categoria;
import com.LocaZilla.model.veiculo.Disponibilidade;
import com.LocaZilla.model.veiculo.TipoDoCombustivel;
import com.LocaZilla.model.veiculo.TipoDoVeiculo;
import com.LocaZilla.model.veiculo.Veiculo;
import static com.LocaZilla.view.TelaCadastroModelo.jComboBoxMarca;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hugo_
 */
public class TelaVeiculo extends javax.swing.JFrame {

    /**
     * Creates new form TelaVeiculo
     */
    public TelaVeiculo() throws Exception {
        initComponents();
        this.setLocationRelativeTo(null);

        ModeloControle modControle = new ModeloControle();
        IVeiculoControle veiculoControle = new VeiculoControle();

        //combobox
        preencherComboBoxModelo();
        preencherComboBoxCategoria();

        IVeiculoControle incluirVeiculo = new VeiculoControle();
        imprimirDadosNaGrid(incluirVeiculo.listagem());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundo = new javax.swing.JPanel();
        jPanelCadastroVeiculo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonVoltarTelaVeiculo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVeiculo = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButtonCadastrarModelo = new javax.swing.JButton();
        jLabelFotoModelo = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jComboBoxSITUACAO = new javax.swing.JComboBox<>();
        jTextFieldANOFabricacao = new javax.swing.JTextField();
        jTextFieldANOModelo = new javax.swing.JTextField();
        jComboBoxMODELO = new javax.swing.JComboBox<>();
        jTextFieldKM = new javax.swing.JTextField();
        jComboBoxCOMBUSTIVEL = new javax.swing.JComboBox<>();
        jComboBoxTIPOVeiculo = new javax.swing.JComboBox<>();
        jTextFieldPRECOcompra = new javax.swing.JTextField();
        jTextFieldPRECOvenda = new javax.swing.JTextField();
        jTextFieldRENAVAM = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButtonAlterar = new javax.swing.JButton();
        jButtonIncluir = new javax.swing.JButton();
        jTextFieldPLACA = new javax.swing.JTextField();
        jComboBoxCATEGORIA = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelFundo.setBackground(java.awt.SystemColor.control);

        jPanelCadastroVeiculo.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 188, 69));
        jLabel1.setText("Cadastro de Veículos");

        jButtonVoltarTelaVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/LocaZilla/imagens/funcoes/Voltar.png"))); // NOI18N
        jButtonVoltarTelaVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarTelaVeiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroVeiculoLayout = new javax.swing.GroupLayout(jPanelCadastroVeiculo);
        jPanelCadastroVeiculo.setLayout(jPanelCadastroVeiculoLayout);
        jPanelCadastroVeiculoLayout.setHorizontalGroup(
            jPanelCadastroVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroVeiculoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButtonVoltarTelaVeiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(226, 226, 226))
        );
        jPanelCadastroVeiculoLayout.setVerticalGroup(
            jPanelCadastroVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroVeiculoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButtonVoltarTelaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTableVeiculo.setBackground(new java.awt.Color(51, 51, 51));
        jTableVeiculo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(240, 188, 69)));
        jTableVeiculo.setForeground(new java.awt.Color(240, 188, 69));
        jTableVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "PLACA", "RENAVAM", "COMPRA", "VENDA", "FABRICAÇÃO", "MODELO", "COMBUSTIVEL", "QUILOMETRAGEM", "TIPO", "MODELO", "DISPONIBILIDADE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVeiculo.setColumnSelectionAllowed(true);
        jTableVeiculo.setFillsViewportHeight(true);
        jTableVeiculo.setFocusCycleRoot(true);
        jTableVeiculo.setGridColor(new java.awt.Color(240, 188, 69));
        jTableVeiculo.setMaximumSize(new java.awt.Dimension(2147483647, 0));
        jTableVeiculo.setMinimumSize(new java.awt.Dimension(75, 0));
        jTableVeiculo.setName(""); // NOI18N
        jTableVeiculo.setPreferredSize(new java.awt.Dimension(300, 0));
        jTableVeiculo.setRowHeight(100);
        jTableVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVeiculoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVeiculo);
        jTableVeiculo.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Id");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Placa");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Disponibilidade");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Fabricação");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Ano Modelo");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Modelo");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Quilometragem");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Tipo Combustível");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Tipo do Veículo");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Preço de Compra");

        jLabel14.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Renavam");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText(" Preço de Venda");

        jButtonCadastrarModelo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCadastrarModelo.setText("Cadastrar Modelo");
        jButtonCadastrarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarModeloActionPerformed(evt);
            }
        });

        jLabelFotoModelo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(240, 188, 69), new java.awt.Color(240, 188, 69)));

        jTextFieldID.setEnabled(false);
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        jComboBoxSITUACAO.setModel(new javax.swing.DefaultComboBoxModel(Disponibilidade.values()));
        jComboBoxSITUACAO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSITUACAOActionPerformed(evt);
            }
        });

        jComboBoxMODELO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Traz os modelos" }));
        jComboBoxMODELO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMODELOActionPerformed(evt);
            }
        });

        jTextFieldKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKMActionPerformed(evt);
            }
        });
        jTextFieldKM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldKMKeyTyped(evt);
            }
        });

        jComboBoxCOMBUSTIVEL.setModel(new javax.swing.DefaultComboBoxModel(TipoDoCombustivel.values()));
        jComboBoxCOMBUSTIVEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCOMBUSTIVELActionPerformed(evt);
            }
        });

        jComboBoxTIPOVeiculo.setModel(new javax.swing.DefaultComboBoxModel(TipoDoVeiculo.values()));

        jTextFieldRENAVAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRENAVAMActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inserir/Alterar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 3, 12), new java.awt.Color(240, 188, 69))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(240, 188, 69));

        jButtonAlterar.setBackground(new java.awt.Color(240, 188, 69));
        jButtonAlterar.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        jButtonAlterar.setForeground(new java.awt.Color(102, 102, 102));
        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/LocaZilla/imagens/funcoes/Alterar.png"))); // NOI18N
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonIncluir.setBackground(new java.awt.Color(240, 188, 69));
        jButtonIncluir.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        jButtonIncluir.setForeground(new java.awt.Color(240, 188, 69));
        jButtonIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/LocaZilla/imagens/funcoes/Mais.png"))); // NOI18N
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(jButtonAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Categoria");

        javax.swing.GroupLayout jPanelFundoLayout = new javax.swing.GroupLayout(jPanelFundo);
        jPanelFundo.setLayout(jPanelFundoLayout);
        jPanelFundoLayout.setHorizontalGroup(
            jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCadastroVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(jPanelFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFundoLayout.createSequentialGroup()
                        .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxMODELO, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCadastrarModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFotoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFundoLayout.createSequentialGroup()
                        .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldANOFabricacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldANOModelo)
                            .addComponent(jComboBoxSITUACAO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPLACA, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelFundoLayout.createSequentialGroup()
                                    .addGap(123, 123, 123)
                                    .addComponent(jLabel14))
                                .addGroup(jPanelFundoLayout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel15)
                                        .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel13))
                                        .addComponent(jLabel17))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFundoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFundoLayout.createSequentialGroup()
                        .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldRENAVAM, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPRECOvenda, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPRECOcompra, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTIPOVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCOMBUSTIVEL, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldKM, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBoxCATEGORIA, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFundoLayout.setVerticalGroup(
            jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundoLayout.createSequentialGroup()
                .addComponent(jPanelCadastroVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFundoLayout.createSequentialGroup()
                        .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11)
                            .addComponent(jComboBoxCOMBUSTIVEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPLACA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxSITUACAO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxTIPOVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(jTextFieldPRECOcompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldANOFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldANOModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)
                                .addComponent(jLabel8)
                                .addComponent(jTextFieldPRECOvenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFundoLayout.createSequentialGroup()
                                .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jTextFieldRENAVAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxCATEGORIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)))
                            .addGroup(jPanelFundoLayout.createSequentialGroup()
                                .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxMODELO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCadastrarModelo))
                            .addComponent(jLabelFotoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preencherComboBoxCategoria() {
        String caminhoArquivo = "./src/com/LocaZilla/Dados/categoria/Categoria.txt";
        File arquivo = new File(caminhoArquivo);

        try {
            BufferedReader br = new BufferedReader(new FileReader(arquivo));
            Object[] linhas = br.lines().toArray();
            jComboBoxCATEGORIA.removeAllItems();

            for (int i = 0; i < linhas.length; i++) {
                String linha = linhas[i].toString();
                String vetorString[] = linha.split(";");
                String categoria = vetorString[1];
                jComboBoxCATEGORIA.addItem(categoria);
            }

        } catch (FileNotFoundException ex) {

            Logger.getLogger(TelaCategoria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void preencherComboBoxModelo() {
        String caminhoArquivo = "./src/com/LocaZilla/Dados/modelo/Modelo.txt";
        File arquivo = new File(caminhoArquivo);

        try {
            BufferedReader br = new BufferedReader(new FileReader(arquivo));
            Object[] linhas = br.lines().toArray();
            jComboBoxMODELO.removeAllItems();

            for (int i = 0; i < linhas.length; i++) {
                String linha = linhas[i].toString();
                String vetorString[] = linha.split(";");
                String modelo = vetorString[1];
                jComboBoxMODELO.addItem(modelo);
            }

        } catch (FileNotFoundException ex) {

            Logger.getLogger(TelaCadastroModelo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void imprimirDadosNaGrid(ArrayList<Veiculo> listaVeiculos) throws Exception {

        try {
            DefaultTableModel model = (DefaultTableModel) jTableVeiculo.getModel();
            ModeloControle modelo = new ModeloControle();

            CategoriaControle categoria = new CategoriaControle();

            model.setNumRows(0);

            Iterator<Veiculo> lista = listaVeiculos.iterator();

            while (lista.hasNext()) {

                String[] saida = new String[13];
                Veiculo aux = lista.next();
                saida[0] = aux.getId() + "";
                saida[1] = aux.getPlaca();
                saida[2] = aux.getRenavam() + "";
                saida[3] = aux.getPrecoDeCompra() + "";
                saida[4] = aux.getPrecoDeVenda() + "";
                saida[5] = aux.getAnoFabricacao() + "";
                saida[6] = aux.getAnoModelo() + "";
                saida[7] = aux.getTipoDeCombutivel() + "";
                saida[8] = aux.getQuilometragem() + "";
                saida[9] = aux.getTipoDeVeiculo() + "";
                saida[10] = modelo.buscar(aux.getModelo().getIdModelo()).getDescricao();
                saida[11] = aux.getSituacao() + "";
                Categoria idCategoria = aux.getCategoria();
                saida[12] = categoria.buscar(idCategoria.getId()).getDescricao();

                model.addRow(saida);
            }

        } catch (Exception erro) {

            JOptionPane.showMessageDialog(this, erro.getMessage());
        }

    }

    private void jButtonVoltarTelaVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarTelaVeiculoActionPerformed
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_jButtonVoltarTelaVeiculoActionPerformed

    private void jButtonCadastrarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarModeloActionPerformed
        // TODO add your handling code here:
        TelaCadastroModelo telaModelo = new TelaCadastroModelo();
        telaModelo.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarModeloActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        try {

            int idModelo = 0;
            int idCategoria = 0;

            ModeloControle objetoModelo = new ModeloControle();
            CategoriaControle objCategoria = new CategoriaControle();
            VeiculoControle objVeiculo = new VeiculoControle();

            Veiculo objeto = new Veiculo(0, jTextFieldPLACA.getText(),
                    Integer.parseInt(jTextFieldRENAVAM.getText()),
                    Float.parseFloat(jTextFieldPRECOcompra.getText()),
                    Float.parseFloat(jTextFieldPRECOvenda.getText()),
                    Integer.parseInt(jTextFieldANOFabricacao.getText()),
                    Integer.parseInt(jTextFieldANOModelo.getText()),
                    jComboBoxCOMBUSTIVEL.getSelectedItem(),
                    Integer.parseInt(jTextFieldKM.getText()),
                    jComboBoxTIPOVeiculo.getSelectedItem(),
                    objetoModelo.buscar(idModelo),
                    jComboBoxSITUACAO.getSelectedItem(),
                    objCategoria.buscar(idCategoria));

            ArrayList<Modelo> lista = objetoModelo.listagemModelo();
            for (int i = 0; i < lista.size(); i++) {

                if (jComboBoxMODELO.getSelectedItem().equals(lista.get(i).getDescricao())) {
                    objeto.setModelo(lista.get(i));
                }
            }

            ArrayList<Categoria> listaCategoria = objCategoria.listagem();
            for (int i = 0; i < listaCategoria.size(); i++) {
                if (jComboBoxCATEGORIA.getSelectedItem().equals(listaCategoria.get(i).getDescricao())) {
                    objeto.setCategoria(listaCategoria.get(i));
                }
            }

            objVeiculo.alterar(objeto);
            imprimirDadosNaGrid(objVeiculo.listagem());

        } catch (Exception erro) {

            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        try {

            int idModelo = 0;
            int idCategoria = 0;

            ModeloControle objetoModelo = new ModeloControle();
            CategoriaControle objCategoria = new CategoriaControle();
            VeiculoControle objVeiculo = new VeiculoControle();

            Veiculo objeto = new Veiculo(0, jTextFieldPLACA.getText(),
                    Integer.parseInt(jTextFieldRENAVAM.getText()),
                    Float.parseFloat(jTextFieldPRECOcompra.getText()),
                    Float.parseFloat(jTextFieldPRECOvenda.getText()),
                    Integer.parseInt(jTextFieldANOFabricacao.getText()),
                    Integer.parseInt(jTextFieldANOModelo.getText()),
                    jComboBoxCOMBUSTIVEL.getSelectedItem(),
                    Integer.parseInt(jTextFieldKM.getText()),
                    jComboBoxTIPOVeiculo.getSelectedItem(),
                    objetoModelo.buscar(idModelo),
                    jComboBoxSITUACAO.getSelectedItem(),
                    objCategoria.buscar(idCategoria));

            ArrayList<Modelo> lista = objetoModelo.listagemModelo();
            for (int i = 0; i < lista.size(); i++) {
                if (jComboBoxMODELO.getSelectedItem().equals(lista.get(i).getDescricao())) {
                    objeto.setModelo(lista.get(i));
                }
            }

            ArrayList<Categoria> listaCategoria = objCategoria.listagem();
            for (int i = 0; i < listaCategoria.size(); i++) {
                if (jComboBoxCATEGORIA.getSelectedItem().equals(listaCategoria.get(i).getDescricao())) {
                    objeto.setCategoria(listaCategoria.get(i));
                }
            }

            objVeiculo.incluir(objeto);
            imprimirDadosNaGrid(objVeiculo.listagem());

        } catch (Exception erro) {

            JOptionPane.showMessageDialog(this, erro.getMessage());

        }

    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jComboBoxCOMBUSTIVELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCOMBUSTIVELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCOMBUSTIVELActionPerformed

    private void jComboBoxSITUACAOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSITUACAOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSITUACAOActionPerformed

    private void jTextFieldRENAVAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRENAVAMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRENAVAMActionPerformed

    private void jTextFieldKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKMActionPerformed


    private void jComboBoxMODELOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMODELOActionPerformed
        // TODO add your handling code here:

        ImageIcon imagem = new ImageIcon("./src/com/LocaZilla/Dados/modelo/ImagemModelo/"
                + jComboBoxMODELO.getSelectedItem() + ".jpg");
        imagem.setImage(imagem.getImage().getScaledInstance(114, 120, 0));
        jLabelFotoModelo.setIcon(imagem);
    }//GEN-LAST:event_jComboBoxMODELOActionPerformed

    private void jTextFieldKMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldKMKeyTyped
        // TODO add your handling code here:
        char e = evt.getKeyChar();
        if (!Character.isDigit(e)) {
            evt.consume();
        }

    }//GEN-LAST:event_jTextFieldKMKeyTyped

    private void jTableVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVeiculoMouseClicked
        // TODO add your handling code here
        try {

            jTextFieldID.setText(jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 0).toString());
            jTextFieldPLACA.setText(jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 1).toString());
            jTextFieldRENAVAM.setText(jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 2).toString());
            jTextFieldPRECOcompra.setText(jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 3).toString());
            jTextFieldPRECOvenda.setText(jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 4).toString());
            jTextFieldANOFabricacao.setText(jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 5).toString());
            jTextFieldANOFabricacao.setText(jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 6).toString());
                    
            String combustivel = jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 7).toString();

            if (combustivel == TipoDoCombustivel.DIESEL.toString()) {
                jComboBoxCOMBUSTIVEL.setSelectedItem(TipoDoCombustivel.DIESEL.valueOf(combustivel));
            }
            if (combustivel == TipoDoCombustivel.ELETRICO.toString()) {
                jComboBoxCOMBUSTIVEL.setSelectedItem(TipoDoCombustivel.ELETRICO.valueOf(combustivel));
            }
            if (combustivel == TipoDoCombustivel.FLEX.toString()) {
                jComboBoxCOMBUSTIVEL.setSelectedItem(TipoDoCombustivel.FLEX.valueOf(combustivel));
            }
            if (combustivel == TipoDoCombustivel.GASOLINA.toString()) {
                jComboBoxCOMBUSTIVEL.setSelectedItem(TipoDoCombustivel.GASOLINA.valueOf(combustivel));
            }
            if (combustivel == TipoDoCombustivel.GNV.toString()) {
                jComboBoxCOMBUSTIVEL.setSelectedItem(TipoDoCombustivel.GNV.valueOf(combustivel));
            }

            jTextFieldKM.setText(jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 8).toString());
            
            String tipoDeVeiculo = jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 9).toString();
            
            if (tipoDeVeiculo == TipoDoVeiculo.HATCH.toString()) {
                jComboBoxTIPOVeiculo.setSelectedItem(TipoDoVeiculo.HATCH.valueOf(tipoDeVeiculo));
            }
            if (tipoDeVeiculo == TipoDoVeiculo.PICKUP.toString()) {
                jComboBoxTIPOVeiculo.setSelectedItem(TipoDoVeiculo.PICKUP.valueOf(tipoDeVeiculo));
            }
            if (tipoDeVeiculo == TipoDoVeiculo.SEDAN.toString()) {
                jComboBoxTIPOVeiculo.setSelectedItem(TipoDoVeiculo.SEDAN.valueOf(tipoDeVeiculo));
            }
            if (tipoDeVeiculo == TipoDoVeiculo.SUV.toString()) {
                jComboBoxTIPOVeiculo.setSelectedItem(TipoDoVeiculo.SUV.valueOf(tipoDeVeiculo));
            }
            
        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, e);
        }


    }//GEN-LAST:event_jTableVeiculoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaVeiculo().setVisible(true);

                } catch (Exception ex) {
                    Logger.getLogger(TelaVeiculo.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCadastrarModelo;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonVoltarTelaVeiculo;
    private javax.swing.JComboBox<String> jComboBoxCATEGORIA;
    private javax.swing.JComboBox<String> jComboBoxCOMBUSTIVEL;
    private javax.swing.JComboBox<String> jComboBoxMODELO;
    private javax.swing.JComboBox<String> jComboBoxSITUACAO;
    private javax.swing.JComboBox<String> jComboBoxTIPOVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFotoModelo;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCadastroVeiculo;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVeiculo;
    private javax.swing.JTextField jTextFieldANOFabricacao;
    private javax.swing.JTextField jTextFieldANOModelo;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldKM;
    private javax.swing.JTextField jTextFieldPLACA;
    private javax.swing.JTextField jTextFieldPRECOcompra;
    private javax.swing.JTextField jTextFieldPRECOvenda;
    private javax.swing.JTextField jTextFieldRENAVAM;
    // End of variables declaration//GEN-END:variables
}
